### ISSUE TITLE
Movie Title Logo & Layout Issue

### ISSUE THREAD

**Issue by saurabhshinde14** [tedhinklater/Jellyfin-Featured-Content-Bar#1]
Hi,

I absoultely like the updates, but I have some issues and feedback. 

![Screenshot 2024-09-13 001743](https://github.com/user-attachments/assets/358e9cc0-6db1-45a7-bb35-cca5e30c13d3)

The title of the movie is bugged in Jellyfin Media Player, but it works fine on browsers. "My media (small)" buttons are on the left side and also aren't centered like it was in previous css. I'm on a 1440p non ultra wide monitor. 

**The following aren't just issues but feedback and suggestions.** 

- You forgot to describe the steps for creating and entering the API Token and a User ID in the readme of this repository. 

- Perhaps you could make the bar more round on the edges and add a drop shadow as it had before. 

- Currently, the new bar appears to be three separate bars. Perhaps you can merge the moving backdrop with the movie title so that it does not leave as much negative space as it does now. 1/3 of the bar is always black behind the movie's title, so maybe you can put the moving picture behind the title as well, and maybe you fade the edge of the image/backdrop from the right side on top of the trailer so when the user hovers the curser over the trailer it will be clear and the fade will go away. It will also make the transition between the title, backdrop, and trailer look more seamless and make the bar appear like one bar.

![Screenshot 2024-09-13 002734](https://github.com/user-attachments/assets/5a1be206-7c6f-4021-a0c9-1eb8b0344052)

I made this quick edit in photoshop to show you what I'm thinking.

![Untitled-1](https://github.com/user-attachments/assets/c70eede9-2dd9-47cf-91c7-cd1e03f9b2ae)

I remember the title, and plot would kind of be in different sides depending on the backdrop in the old featured bar.

I understand that you can only do so much with HTML. 

Thank you for this!

**Comment by tedhinklater** [comment]
Hey thanks for taking the time, I didn't realise the logo was messed up on JMP! 

You don't need to enter an API key or UserID anymore! Thanks to BobHasNoSoul:

"because i didnt like the js being able to have plain text api key and userid.. i have rewrote it to make the user get their own automatically using javascript and having them in the sessionstorage, this wont save forever so dont worry it just gets seen by the slideshow. also it no longer leaks content out like the backdrop or logos or descriptions to non logged in users, it will only work if they are using it inside of jellyfin after logging in.. so all around more secure"

Your edit does look nice... should be easy enough! I'll get on it tonight. Thanks again for taking the time to help :) It's appreciated

**Comment by saurabhshinde14** [comment]
I appreciate the quick response. 

I didn't look at the code, but you sure cut out a lot of hassle that you had to go through with entering the api and user ID. 

I sent you a DM on jellyfin forum regarding the same issue with the UI a couple of hours ago, and made a thread about it.

I was scratching my head for a bit because the UI was messed and I couldn't figure out why, and then I came across these updates. 

If you have a discord then forward me your username on JF forum DM.

**Comment by tedhinklater** [comment]
Ahh you're Sash, nice to see you :D Ok the logo on JMP's fixed (it didn't like being a "top: ~%" and I've made it look like your edit as much as I can tonight, I've added a line to Finality to centre those library buttons. You'll need to replace the part inserted into home-html.chunk.js and spotlight.html 

I'll try the fade/hover trailer effect tomorrow, thanks again!

**Comment by tedhinklater** [comment]
Oh damn thanks, I think your display scale is set to 150% (but it shouldn't look like that) I'm on it

**Comment by saurabhshinde14** [comment]
My display scale is to 100% and so is the browser. Did you happen to change the width of the bar? It looks very big now.

**Comment by tedhinklater** [comment]
Yeah it was a bug with Finality, the 150% OS scale triggers the 768p sizing, should be fixed now

**Comment by saurabhshinde14** [comment]
is the new bar supposed to be that big? I tested it without finality as well, and it would still crop some info from the bar. And like I mentioned I never use 150% scale on my display.

![Screenshot 2024-09-13 153312](https://github.com/user-attachments/assets/a678101c-5256-47de-9947-90e5830e498c)

**Comment by tedhinklater** [comment]
Sorry I did see that you said you're not at 150%, just that's how I could replicate what you screenshotted. It's definitely the different screen-width media queries that are the problem cause just removing them looks better, just needs a tweak.

**Comment by tedhinklater** [comment]
I've uploaded the new spotlight.html could you give it a try? Fingers crossed

**Comment by saurabhshinde14** [comment]
I'm on the same boat haha

![Screenshot 2024-09-13 160946](https://github.com/user-attachments/assets/d625803b-d445-4fbf-8d54-fdfcb96547a6)

![Screenshot 2024-09-13 161038](https://github.com/user-attachments/assets/0cc51582-d06d-4676-9c23-62068f961ac7)

**Comment by saurabhshinde14** [comment]
I also want to mention that the line that you added to center the media button only works on Chrome, and not on JMF, Firefox etc. Also. messes up the settings page.

I reported that issue on Finality repo with screenshots.

**Comment by tedhinklater** [comment]
uploaded a new spotlight

**Comment by saurabhshinde14** [comment]
It has exact dimensons like the one I linked in the previous reply. I'm refereeing to the "Love Lies Bleeding" bar. The only different is that the age rating of the movie has moved a bit to the left. And the genre, ratings, and summary goes out of bounds with default jf theme.

**Comment by tedhinklater** [comment]
sorry I uploaded another spotlight (fixed the age rating position) just as you were writing this. 
I'm going to figure out how to make it work with/without finality

**Comment by tedhinklater** [comment]
ohhh it's the 100vh height of the slide right at the start of the code, I got it

**Comment by saurabhshinde14** [comment]
Let me know when to download 

I got things mixed up too haha 
![Screenshot 2024-09-13 172151](https://github.com/user-attachments/assets/b53d0384-a369-4c35-8f6a-99c815e69ca8)

**Comment by tedhinklater** [comment]
Ok paste this into home-html.randomstring.chunk.js

```js
<style>.featurediframe { width: 95vw; height: 23.5em; display: block; border: 0px solid #000; margin: 0 auto; margin-bottom: 40px} @media (min-width: 2000px) { .featurediframe {height: 23em; min-height: 50vh;}}</style><iframe class="featurediframe" src="/web/avatars/spotlight.html"></iframe>
```

and there is a new spotlight

**Comment by saurabhshinde14** [comment]
So, I downloaded the new spotlight.html and copied the line into home html. The bar works on Finality and the width is a bit bigger compared to JF default. It also doesn't work on JF default theme.

I reset my browser to make sure I'm not missing anything. 

![Screenshot 2024-09-13 181030](https://github.com/user-attachments/assets/37ba6a3a-d7f1-4e96-93d2-1b04f8c768fe)
![Screenshot 2024-09-13 181131](https://github.com/user-attachments/assets/8f7d977c-41bd-43d3-9469-82c275116ae8)
![Screenshot 2024-09-13 181246](https://github.com/user-attachments/assets/051a4c19-25cc-4114-9b69-403db56265e7)
![Screenshot 2024-09-13 181205](https://github.com/user-attachments/assets/b63ae557-6da2-4005-af50-a25d9300ad38)

**Comment by tedhinklater** [comment]
That's so bizarre.. I'm using 2560x1440 in JMP and get this
![1](https://github.com/user-attachments/assets/f475d377-3d6f-42fe-aaa1-c670ee650f58)

**Comment by tedhinklater** [comment]
ok there was another ".slide 100vh" hiding in the code, I think that was messing it up, I've also changed this code 1 more time

```js
<style>.featurediframe { width: 95vw; height: 23.5em; display: block; border: 0px solid #000; margin: 0 auto; margin-bottom: 40px} @media (min-width: 2000px) { .featurediframe {height: 23.5em; min-height: 33vh;}}</style><iframe class="featurediframe" src="/web/avatars/spotlight.html"></iframe>
```

and a new spotlight is up. Really need to figure this out :D it's driving me crazy

**Comment by saurabhshinde14** [comment]
Okay, I think I know what the issue is

Could you check the scale of your browser? The scale doesn't matter when you're using Finality as it scales everything together, but it doesn't work like that with Jellyfin Default Theme.

Here's what's happening:

https://streamable.com/0e2yku

https://streamable.com/ohc2uh

**Comment by tedhinklater** [comment]
```js
<style>.featurediframe { width: 95vw; height: 23.5em; display: block; border: 0px solid #000; margin: 0 auto; margin-bottom: 40px} @media (min-width: 2000px) { .featurediframe {height: 18em; font-size: 175%;} .layout-desktop #homeTab .sections.homeSectionsContainer {margin-top: -3em !important;}}</style><iframe class="featurediframe" src="/web/avatars/spotlight.html"></iframe>
```
This is at 1440p with the updated code in home-html

https://streamable.com/kaexmf

**Comment by saurabhshinde14** [comment]
It is finally working on both Finality, and JF Default Theme. Thank you so much! 

The code that you changed to center the "My media" buttons isn't working it seems. The buttons are back on the left side. 
Could you center it or just upload the old finality.css you had? Thanks again!

**Comment by tedhinklater** [comment]
Yeaaahh!! ok awesome thanks for the help man you've been crazy patient

I'll fix the My Media buttons on finality now

**Comment by saurabhshinde14** [comment]
Thanks a lot! Does it take a bit to update the import .css? I reset and cleared the cache of my browsers, but I don't see any changes so I just copied the entire css instead of importing it.

**Comment by tedhinklater** [comment]
It does, sometimes days but I've sent a [purge request](https://www.jsdelivr.com/tools/purge) so it should refresh soon, usually between 1-24 hours

**Comment by tedhinklater** [comment]
I just noticed the countdown-bar along the bottom (when there is no trailer) needs fixing, I'll get it

**Comment by saurabhshinde14** [comment]
Not sure what is causing this. 
![Screenshot 2024-09-13 204549](https://github.com/user-attachments/assets/522b8af0-7230-49db-bbb3-c8d77c62990f)

[customcss.txt](https://github.com/user-attachments/files/16995981/customcss.txt)

**Comment by tedhinklater** [comment]
I think it's the order of the css try this

[customcss.txt](https://github.com/user-attachments/files/16996151/customcss.txt)

**Comment by saurabhshinde14** [comment]
The backdrop that you enable from settings isn't working anymore.

**Comment by tedhinklater** [comment]
https://github.com/user-attachments/assets/afafd396-3da4-477b-8ef8-500d68655825

**Comment by saurabhshinde14** [comment]
That looks so good! Maybe you could move the image a bit more to teh right or decrease the amount it fades on to the video. 

And the backdrops aren't working for me anymore. Did you inherit any code from BobHasNoSoul? these codes do the same right?

[--- Inherited from httpsgithub.com.txt](https://github.com/user-attachments/files/16996603/---.Inherited.from.httpsgithub.com.txt)

**Comment by tedhinklater** [comment]
I've changed the gradient on the mask to show more of the image with a faster curve

I'm using the customcss.txt I sent you and purged my cache to be sure, have you got Backdrops enabled under Display Settings?

That spotlight I linked before moved the countdown-bar (when there's no trailer) to the top of the slide

**Comment by saurabhshinde14** [comment]
I think there was a bit of miscommunication. I was asking you to move the image to left because the image covers more than 1/3rd of the video right now. Don't mind my drawing. 

![Screenshot 2024-09-13 222859](https://github.com/user-attachments/assets/77b7d941-f721-4b1c-b79c-9cd73731507b)

Honestly, you be the judge because you'd know what looks good in real time when you make changes. 

The backdrops weren't working because I was using 3 different codes that does the same thing. I had Bob's code, and the one you had in finality repo "scrolling.css". 

I'm not sure if I saw a countdown bar. I do know that whenever I launch jellyfin-web I have to refresh the page for the bar to show up because it wouldn't show up and that space is kind of empty after I start the jellyfin web ui or JMP.

**Comment by tedhinklater** [comment]
Like this ? ![feat2](https://github.com/user-attachments/assets/8d98e100-0c2e-4a54-9fa6-34b48c4ea69b)

That's ok man thanks for the assist :)

**Comment by saurabhshinde14** [comment]
Yes, that looks great! 

But some trailers don't have the 16:9 aspect ratio so it kind of looks like this. 

![Screenshot 2024-09-13 234233](https://github.com/user-attachments/assets/de8105a6-85aa-4e94-b45d-c1bc534f21c2)

Could you tell me or comment out the parameters I need to change to play with the fade? So users can switch it locally according to their taste.

**Comment by saurabhshinde14** [comment]
It turned out so well btw. 

Thanks for putting so much efforts into it.

**Comment by tedhinklater** [comment]
I've made one more update to move the backdrop and adjust the trailer size

This is the fade btw 

```css
		.video-player { mask-image: linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.25) 3%, rgba(0, 0, 0, 0.5) 7%, rgba(0, 0, 0, 0.75) 15%, rgba(0, 0, 0, 0.9) 25%, rgba(0, 0, 0, 1) 35%, rgba(0, 0, 0, 1) 100%);
		-webkit-mask-image: linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.25) 3%, rgba(0, 0, 0, 0.5) 7%, rgba(0, 0, 0, 0.75) 15%, rgba(0, 0, 0, 0.9) 25%, rgba(0, 0, 0, 1) 35%, rgba(0, 0, 0, 1) 100%); transition: mask-image 5s ease, -webkit-mask-image 5s ease;}
		.slide:hover .video-player { mask-image: none; -webkit-mask-image: none;}
```
Those lines are at the end of the <style> section in spotlight.html (line 66)
and I used [non-boring-gradients](https://non-boring-gradients.netlify.app/) to generate the curve

**Comment by saurabhshinde14** [comment]
I like the changes. I was actually going to tell you to do the same. 

I'm not sure if this is possible, but setting up a standard 1080p or 1440p with 50% volume s for every video would work well because right now so videos play at 480p if not 360p and some blast volume.

**Comment by tedhinklater** [comment]
I've set the YT player volume to 50% and have changed & moved the next-button (good ideas!) but for the trailer ratios, it would probably have to use python to analyze the video for black bars and adjust the container... you get the idea :/ sorry

**Comment by saurabhshinde14** [comment]
Yes, I figured so. Thanks for the updates though. I really apperciate it and this project turned out well. 

You can take inspiration from this for the full screen bar. It's same but the dimensons of the bar are big.
![image](https://github.com/user-attachments/assets/309d1968-84b3-4d9b-895e-7ae3f662c3bc)

You can close this issue now. If anything comes up I'll reach out to you on JF forum. And I'll see if I can get the thing working with python. Thanks again!
