### ISSUE TITLE
Featured Bar doesn't work on Android TV

### ISSUE THREAD

**Issue by L10Messi10** [tedhinklater/Jellyfin-Featured-Content-Bar#10]
I managed to make this work on web ui and phone, but when I tried to have this on Android TV nothing appeared.

**Comment by tedhinklater** [comment]
This version only works on desktop/mobile, like you said

There was an older version that didn't have trailers that may work on simpler devices (doesn't have the trailers) 

https://forum.jellyfin.org/attachment.php?aid=3635

Unfortunately, the TV app for Jellyfin doesn't support the trailer update

**Comment by L10Messi10** [comment]
Will there be a plan on supporting the said platform?


- The link you provided. Is this the same process in Spotlight?

**Comment by tedhinklater** [comment]
My bad I forgot to give the forum post link earlier https://forum.jellyfin.org/t-featured-content-bar

These were the instructions for that one at the time:

You can do it like this on Windows

    Download slideshow.html
    Enter your UserId into line 11 of slideshow.html (Get your UserID by going to the Jellyfin Dashboard, go to the Users tab, click your username. Your UserId is the last string in the address bar after the = sign)
    Enter your API key into line 12 of slideshow.html (Go to Dashboard, API Keys tab, click the + and create a key for FeaturedSlideshow)
    Go to your jellyfin-web folder (C:\Program Files\Jellyfin\Server\jellyfin-web) and create a folder named avatars and drop slideshow.html in that folder
    (Important: Open Notepad with Administrator rights, or use Notepad++ for this) In the jellyfin-web folder, open the file home-html.RANDOMSTRINGHERE.chunk.js
    Ctrl+F and search for data-backdroptype="movie,series,book"> Paste this after the >
    Code:
    <style>.featurediframe { width: 89vw; height: 300px; display: block; border: 1px solid #000; margin: 0 auto}</style> <iframe class="featurediframe" src="/web/avatars/slideshow.html"></iframe>
    Save the file.
    Empty your browser's cached web content (Ctrl+F5 or empty it from your browser's Cookies and Site Data settings section)

**Comment by tedhinklater** [comment]
> Will there be a plan on supporting the said platform?

It's not up to me :( the jellyfin tv team are the ones who can make it happen
