### ISSUE TITLE
Why the back button is not showing?

### ISSUE THREAD

**Issue by Isaiasgamedev** [tedhinklater/Jellyfin-Featured-Content-Bar#11]
Why the back button is not showing?
![Screenshot_2](https://github.com/user-attachments/assets/712033f9-e2ed-410f-b930-a96acb440b47)

**Comment by tedhinklater** [comment]
what back button?

**Comment by tedhinklater** [comment]
also why is Dune Prophecy an anime music video haha

**Comment by Isaiasgamedev** [comment]
the back button like the skip button, but hes not showing 
![Uploading 1.png…
![2](https://github.com/user-attachments/assets/324e0310-6ccf-4ad3-bcf4-56cb07b3b559)
]()
Question: also why is Dune Prophecy an anime music video haha?
Thats my fault i need to put the right metadata haha

**Comment by Isaiasgamedev** [comment]
![1](https://github.com/user-attachments/assets/22bc6aa6-0a4a-461c-ad78-04818facf1f7)

**Comment by Isaiasgamedev** [comment]
![2](https://github.com/user-attachments/assets/9f090997-1885-4dea-b40e-7b804cfcfc5d)

**Comment by Isaiasgamedev** [comment]
you can see the same behavior on you prints on repository too

**Comment by tedhinklater** [comment]
Ohh I started that and never finished, thanks

**Comment by Isaiasgamedev** [comment]
you need to accept the pull request i get the changes and put on spotlight fullscreen and works fine on here, so i belive you need just to update the spotliths

**Comment by tedhinklater** [comment]
I tested the version you sent but the back-button just changes to a random movie, not the previous one

**Comment by tedhinklater** [comment]
If you can fork the current version, and make a PR that would be best, thanks for your help

**Comment by tedhinklater** [comment]
Done!
