### ISSUE TITLE
We need to make that work on tv app

### ISSUE THREAD

**Issue by Isaiasgamedev** [tedhinklater/Jellyfin-Featured-Content-Bar#12]
i use tv app on LG e now the app showing this big space haha 
![WhatsApp Image 2024-11-21 at 19 43 02 (1)](https://github.com/user-attachments/assets/b56c6fe7-f3d6-4e41-85be-bfaf088f13ba)
![WhatsApp Image 2024-11-21 at 19 43 02](https://github.com/user-attachments/assets/e037a03e-0d8a-4c85-88c3-62ca7ecba33e)
but i beleve we can made that work fine on tv too

**Comment by Isaiasgamedev** [comment]
Testing on here i made a texte like "HAUHUAHUAHUAHUAHUAHUAHUAHUAHUAHUAHUAHU" in the iframe e that text is showing on tv sou when we change the file home-html.RANDOMSTRINGHERE.chunk.js e its work, my guess is this path src="/web/ui/spotlight.html"></iframe> dont exist on tv app

**Comment by tedhinklater** [comment]
https://github.com/tedhinklater/Jellyfin-Featured-Content-Bar/issues/10
