### ISSUE TITLE
Iframe protection

### ISSUE THREAD

**Issue by PierreKy-org** [tedhinklater/Jellyfin-Featured-Content-Bar#13]
Hello everyone, 

I tried to intsall the featured content bar on my jellyfin container (https://hub.docker.com/r/linuxserver/jellyfin) and I have the banner.

But, as you can see, my browser block the content. 

![error](https://github.com/user-attachments/assets/ff89a1fe-eaaf-401f-98e8-b08dbf87987a)

I tried with chrome too. I have the same issue

Do you have a way to solve this problem ? 

Thanks a lot for your help !

**Comment by tedhinklater** [comment]
did you go to the spotlight.html page and download the file? Or did you possibly right-click the like and do **Save Link** ?

I've updated the guide to be a bit clearer.

**Comment by PierreKy-org** [comment]
Yes I can do it, do you want a pastebin of spotlight.html ?

**Comment by tedhinklater** [comment]
Instead of downloading spotlight.html I think a lot of people have been right-clicking the link to spotlight.HTML and using Save As... 

This doesn't download spotlight.HTML but it downloads the github page for it.

A pastebin would be appreciated, to check

**Comment by PierreKy-org** [comment]
I know how to download the html file, I put in the good folder (/usr/share/jellyfin/web/ui/spotlight.html )
I put the API key inside and modify the home-html[numbers].chunk.js to integrate the iframe into the home page. 

I don't think the issue it's from this part, it's more about CORS policy something like that

**Comment by tedhinklater** [comment]
Since the update it also needs List.txt in the ui folder

I've updated the guide, with a docker section

If your spotlight.html begins with `<!DOCTYPE html><html  lang="en"` It's the wrong one. You need to download this one

![spotlight.html](https://i.imgur.com/te4j40P.png)

**Comment by PierreKy-org** [comment]
For the List.txt, I saw and add the file into my container. 

Also this is my spotlight.html, I think it's good 

![image](https://github.com/user-attachments/assets/1a6cb27a-ee7f-4ff9-b09c-2b5dbf34cae5)

**Comment by PierreKy-org** [comment]
I found the problem, it's my reverse proxy caddy, it had the X-Frame-Options as DENY and it blocked the content. 

Perhaps we could add a warning in the README.md.

**Comment by tedhinklater** [comment]
It looks like you've done it right, is it a permissions issue? 

```
chmod 644 /usr/share/jellyfin/web/ui/spotlight.html
chmod 644 /usr/share/jellyfin/web/ui/spotlight.html
chmod 644 /usr/share/jellyfin/web/home-html.chunk.js
```

Or maybe the changes are getting lost on restart? Maybe they need to be baked into a custom image?

**Comment by PierreKy-org** [comment]
Yess, I ask for a #17 if it's ok for you

**Comment by tedhinklater** [comment]
that's a fantastic addition to the guide thank you so much, well done for figuring it out!
