### ISSUE TITLE
Next button always moves to random slide, ignoring potential use of the back button

### ISSUE THREAD

**Issue by Digital-Yeti** [tedhinklater/Jellyfin-Featured-Content-Bar#15]
Currently every time you select _Next_, it will navigate to a random slide, even if you have previously selected the back option thus locking in the correct next slide.

Expected behavior: Select _forward_ from slide showing Movie_1 to reveal a new slide, Movie_2. Press _back_ to return to Movie_1. Press _forward_ again and be brought back to Movie_2

Current behavior: Select _forward_ from slide showing Movie_1 to reveal a new slide, Movie_2. Press _back_ to return to Movie_1. Press _forward_ again and be brought to Movie_3

**Comment by tedhinklater** [comment]
Woops! Thanks for the info, it's fixed now
