### ISSUE TITLE
Feature request: Randomize custom list

### ISSUE THREAD

**Issue by chrisbehectik** [tedhinklater/Jellyfin-Featured-Content-Bar#18]
The ability to randomize which item appears in the content bar based on a custom list?

I realize I could just randomize the list myself in the List.txt file but it would be cool to get an actual random item from the list.

If this is possible by editing the spotlight.html, my apologies and please point me in the right direction!

**Comment by tedhinklater** [comment]
nope I made a mistake, don't code from a phone!

**Comment by chrisbehectik** [comment]
Thanks for your work on this.

Not sure if my custom CSS is conflicting but your last change to spotlight.html made the feature bar dissapear.

**Comment by tedhinklater** [comment]
ah sorry, it wasn't fetching anything from outside the list, i'll get on it

**Comment by tedhinklater** [comment]
ok the new one works if List.txt has no content
