### ISSUE TITLE
Feature request: Trailer and next item time limit

### ISSUE THREAD

**Issue by chrisbehectik** [tedhinklater/Jellyfin-Featured-Content-Bar#19]
The ability to set a time limit for each trailer and consequent action of changing to next item. I believe currently it plays the whole trailer before moving to the next item.

Example: Spotlight bar starts trailer and after 45s change to next item.

Again, if this is possible by editing the spotlight.html, my apologies and please point me in the right direction!

**Comment by tedhinklater** [comment]
In spotlight.html search for `shuffleInterval`

Its currently set to 15000 (15 seconds)

**Comment by tedhinklater** [comment]
Ok in spotlight.html search for trailerMaxLength 

the default is 0, so it changes slides when the trailer dies of natural causes.
Set it to 45000 for 45 seconds etc

**Comment by tedhinklater** [comment]
Ok despite the flu I am pretty sure it's all done, no more repeated slides, List.txt is randomized, user's age-ratings are considered and shuffleInterval works
