### ISSUE TITLE
Going into the 'Live Tv' Menu will incorrectly play a trailer in the background

### ISSUE THREAD

**Issue by Digital-Yeti** [tedhinklater/Jellyfin-Featured-Content-Bar#20]
This does not happen in the Movies and Shows menus.

**Comment by Digital-Yeti** [comment]
This report might not be accurate. Somehow trailers are still playing in the background on occasion after watching Live tv.

**Comment by tedhinklater** [comment]
I'm going to test this for a day or so, if you want to test the new version it's here:

[home-html.chunk.js](https://pastebin.com/NwApq1vL)
[spotlight.html](https://pastebin.com/px4JMDkG)

Basically the bar will be hidden unless the Home tab is visible, and will mute unless hovered. I haven't been able to reproduce that bug but the hover trick should fix any background audio stuff.
