### ISSUE TITLE
Feature Request: Hide the featured content bar in other homepage tabs (Request mod, Favorites, Trailers, etc)

### ISSUE THREAD

**Issue by Ryah** [tedhinklater/Jellyfin-Featured-Content-Bar#21]
For example, if you use both the featured content bar and the one mod where it [adds a request tab to the homepage](https://github.com/BobHasNoSoul/jellyfin-mods?tab=readme-ov-file#add-requests-tab), it overlays the iFrame for the requests above the content bar and looks really weird. 

One possible solution I've thought of is having the featured content bar hide/show depending on css class?

**Comment by tedhinklater** [comment]
I have a method to hide it, it's just getting it to mute when homeTab isn't active

**Comment by tedhinklater** [comment]
I'm going to test this for a day or so, if you want to test the new version it's here:

[home-html.chunk.js](https://pastebin.com/NwApq1vL)
[spotlight.html](https://pastebin.com/px4JMDkG)
