### ISSUE TITLE
Jellyfin Featured bar not appear

### ISSUE THREAD

**Issue by TheCaptainCook** [tedhinklater/Jellyfin-Featured-Content-Bar#29]
Hi, 

I have tried everything but the featured bar does not appear on the Jellyfin app. Does it not appear on the Jellyfin app or I am doing something wrong?

Thanks
The Captain Cook

**Comment by tedhinklater** [comment]
Does it appear in the browser? If so, try deleting the contents of C:\Users\Username\AppData\Local\Jellyfin Media Player\Cache

**Comment by TheCaptainCook** [comment]
Yes, the featured bar appears on the browser on both mobile and computer but the problem is the Jellyfin app. The example you can see from the images posted below. 
For reference - 1 Jelly - Desktop jellyfin in browser 
                         2 Jelly - Mobile Jellyfin in browser
                         3 Jelly - Mobile Jellyfin in jellyfin client / jellyfin app.

![1 jelly](https://github.com/user-attachments/assets/f00eeb76-9513-46cf-9f7e-35320b4cb087)
![2 jelly](https://github.com/user-attachments/assets/30a1f2b6-ed02-44ac-aca3-9707064464a7)
![3 jelly](https://github.com/user-attachments/assets/de136b6a-29fc-4e26-967d-ecd77da0d437)

Thanks for the quick reply though. 
The Captain Cook.

**Comment by tedhinklater** [comment]
ahh ok, maybe long-press the App and go to Storage and empty the cache that way?

**Comment by TheCaptainCook** [comment]
Ah.. it shows up now.

Thanks very much. Closing it ...

Solved....
