### ISSUE TITLE
Issue with the Plugin's Frame Dimensions

### ISSUE THREAD

**Issue by jessym38** [tedhinklater/Jellyfin-Featured-Content-Bar#30]
Hello,

Thank you for your plugin, it works great! However, I am encountering an issue with the dimensions of the spotlight bar frame as well as the video frame, which appears to be misaligned.

![Capture d’écran 2024-12-12 115152](https://github.com/user-attachments/assets/d431a482-d2a9-4fb4-8425-5fcb3fd1e2d8)

mobile version:
![Screenshot_2024-12-12-12-36-47-21_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/03e1c72e-262c-4d8c-922d-4c82075f21e7)

**Comment by tedhinklater** [comment]
Sorry about that, thanks for letting me know, it's fixed in the new [home-html](https://github.com/tedhinklater/Jellyfin-Featured-Content-Bar/blob/main/home-html.chunk.js) and [spotlight](https://github.com/tedhinklater/Jellyfin-Featured-Content-Bar/blob/main/spotlight.html) files
