### ISSUE TITLE
In Jellyfin in the Xbox X doesn't work

### ISSUE THREAD

**Issue by darknebular** [tedhinklater/Jellyfin-Featured-Content-Bar#31]
Hello,

Using Jellyfin in Xbox-X the Featured Bar doesn't load.

Regards.

**Comment by tedhinklater** [comment]
Yeah, since we are editing jellyfin-web, it only affects clients using the web wrapper (browser, Jellyfin Media Player etc)

**Comment by darknebular** [comment]
Then, this It's normal, correct?
![image](https://github.com/user-attachments/assets/d7591f90-6197-4b72-a8d1-a73fb0c6c89b)
