### ISSUE TITLE
Feature Request : Option to force desktop interface to behave like mobile

### ISSUE THREAD

**Issue by Mercedezs** [tedhinklater/Jellyfin-Featured-Content-Bar#5]
I would like to request a feature that allows all desktop interfaces to behave like the mobile version. The idea is to define an option or mode that treats the entire interface as mobile, regardless of the device or screen resolution being used.

The main reason for this request is to make the trailer button, available in the mobile version, also accessible on the desktop version, without automatically starting the trailer. This would improve the user experience, as the trailer would only start when the button is pressed, just like on mobile devices.

Desired functionality:

Add an option to define the desktop interface as mobile.
On the desktop version, the trailer should not auto-start but only play when the user presses the play button, mirroring mobile behavior.
Reason:
This behavior would give users more control over when trailers are started and improve accessibility, especially for those who prefer the simplified interface of the mobile version

**Comment by tedhinklater** [comment]
Seth's working on a big update so when that's done we can work on these features

**Comment by sannidhyaroy** [comment]
Yep, I thought that the mobile design looked wayy cooler. I'd want that design on the desktop too... It's upto preference, so maybe give users a choice to choose which they prefer.

**Comment by tedhinklater** [comment]
well it looks like it's taking a bit longer than expected with the update 

I've made a mobile version for desktop screens now, if you could let me know of any bugs it'd be appreciated

**Comment by tedhinklater** [comment]
![Screenshot 2024-11-15 205459](https://github.com/user-attachments/assets/bd144dc0-dbe3-4672-8533-44c28c48ab2a)

[mobile layout but for desktop screens](https://github.com/tedhinklater/Jellyfin-Featured-Content-Bar/tree/main?tab=readme-ov-file#mobile-layout-but-on-desktop-sized-screens)
