### ISSUE TITLE
I am a noob. Can anyone teach me how to install this for Linux Debian on Proxmox? Thank you :)

### ISSUE THREAD

**Issue by jacky1357** [tedhinklater/Jellyfin-Featured-Content-Bar#7]
I am a noob. Can anyone teach me how to install this for Linux Debian on Proxmox? Thank you :)

**Comment by tedhinklater** [comment]
Hey Jacky this is the [BobHasNoSoul](https://github.com/bobhasnosoul) (original creator) method for Linux installation https://github.com/bobhasnosoul/jellyfin-featured?tab=readme-ov-file#linux

Bear in mind, we switched the folder name "avatars" to "ui" plus a lot of updates to the code itself, so it's quite different and won't be a word-for-word installation method, you will at least have to edit the file autoInstall.sh from his repo before using it
